# @package eval.tofu.metrics.extraction_strength_retain_para
defaults:
  - ../../data/datasets@datasets: TOFU_QA_retain_para
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: extraction_strength
batch_size: 32

datasets:
  TOFU_QA_retain_para:
    args:
      hf_args:
        name: retain_perturbed