# @package eval.tofu.metrics.extraction_strength_ra
defaults:
  - ../../data/datasets@datasets: TOFU_QA_ra
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: extraction_strength
batch_size: 32

datasets:
  TOFU_QA_ra:
    args:
      hf_args:
        name: real_authors