# @package eval.tofu.metrics.extraction_strength_forget_pert
defaults:
  - ../../data/datasets@datasets: TOFU_QA_forget_pert
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: extraction_strength
batch_size: 32

datasets:
  TOFU_QA_forget_pert:
    args:
      hf_args:
        name: ${eval.tofu.forget_split}_perturbed