# @package eval.tofu.metrics.extraction_strength_wf_pert
defaults:
  - ../../data/datasets@datasets: TOFU_QA_wf_pert
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: extraction_strength
batch_size: 32

datasets:
  TOFU_QA_wf_pert:
    args:
      hf_args:
        name: world_facts_perturbed